version: "3.9"

services:
  db:
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_DB: "goeventbooking"
      POSTGRES_USER: "goeventbooking"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  goeventbooking:
    image: goeventbooking
    build:
      context: ../api
      dockerfile: ../api/Dockerfile
    ports:
      - 8080:8080

volumes:
  db-data:
